name: SSH Servers

on:
  workflow_dispatch:  # 手动触发工作流
  schedule:
    - cron: "15 5 1 * *"  #每个月5点15分运行

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH and SSHPass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Get ACCOUNTS_JSON from Secrets
        id: get-accounts
        run: |
          echo "$ACCOUNTS_JSON" > accounts.json
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}  # 从 GitHub Secrets 获取服务器账号信息

      - name: Generate SSH Commands
        id: generate-ssh-commands
        run: |
          echo "#!/bin/bash" > sshpass.sh
          while IFS= read -r account; do
            username=$(echo "$account" | jq -r '.username')
            password=$(echo "$account" | jq -r '.password')
            ssh=$(echo "$account" | jq -r '.ssh')
            
            # 生成 SSH 连接命令
            echo "echo \"链接： $username@$ssh\"" >> sshpass.sh
            echo "sshpass -p '$password' ssh -o StrictHostKeyChecking=no '$username@$ssh' 'echo 使用GitHub Actions登录成功'" >> sshpass.sh
          done < <(jq -c '.[]' accounts.json)
          chmod +x sshpass.sh

      - name: Execute SSH Commands
        run: ./sshpass.sh
